### ISSUE TITLE
Question about extends

### ISSUE THREAD

**Issue by noglitchyo** [nazar-pc/docker-webserver#20]
Hi @nazar-pc ,

I am using your stack from not so long and everything is working smoothly since then.
Well, I came to a point where I need to use 2 extra extensions for PHP.
So I decided to extend your webserver:php-fpm image in my custom image.

This is what I did:
```

FROM nazarpc/webserver:php-fpm
MAINTAINER Maxime Elomari <maxime.elomari@gmail.com>

RUN apt-get update

RUN apt-get install -y --no-install-recommends libxslt1-dev
RUN docker-php-ext-install xsl

RUN apt-get install -y --no-install-recommends icu-devtools libicu-dev
RUN docker-php-ext-install intl

RUN curl -sS https://getcomposer.org/installer | \
  php -- --install-dir=/usr/local/bin --filename=composer

# Cleanup
RUN apt-get clean \
RUN rm -rf /var/lb/apt/lists/*
```

Thing is, I ended up with the following error while building my image:

```
/usr/local/bin/docker-php-ext-enable: 81: /usr/local/bin/docker-php-ext-enable: cannot create /usr/local/etc/php/conf.d/docker-php-ext-xsl.ini: Directory nonexistent
The command '/bin/sh -c docker-php-ext-install xsl' returned a non-zero code: 123
```
I am quite new to Docker and I might not know how to do it in the proper way. My guess is that I probably miss something. Is this related to your image? Or do I need to run something else before I could do what I am trying to do. Would you mind pointing me in the right direction please?

For the record, I checked the commands before by executing them directly in the container, using 
 `docker-compose exec php /bin/sh`
Everything went well, and the extensions were installed.

**Another question/suggestion:**

I read the issue about the composer included in the stack. It is interesting that you decided to put it in the ssh container instead of the php container. From my point of view, would not be better if the composer was installed in the php container? Let me explain why:

For my application, like explained previously, I required 2 PHP extensions. But if I install them on the php container, it is only for it's php-cli and not for the ssh container BUT I am using the composer installed on the ssh container which is using the php-cli of ssh container as well. So both of my extensions are missing, which is normal, but quite inconvenient. I have to reinstall them, and even more because all the extensions installed for the php container are missing from the php cli of the ssh container.

Let me know what you think.

Thank you!

**Comment by nazar-pc** [comment]
> My guess is that I probably miss something. Is this related to your image?

A big part of work done with this image is to ensure upgradability of images, so that you'll not stuck with old insecure version of, let's say, PHP. However, I was also aiming to preserve configuration customizations while doing actual upgrade. I order to achieve this all configuration is stored in data-only container and linked to every other image. As linking directories will override existing directories in those containers, default directories with configuration were moved to new locations and only copied back on container start if no existing configuration already exists.

What you need to do is pretty simple. As on [this line](https://github.com/nazar-pc/docker-webserver/blob/b265dd910fcf376885185a38ddb1a74906c764bf/php-fpm/Dockerfile#L32) just move it back before installing any addition modules and forth to keep compatibility with image in this repository (if you're upgrading from stock image in this repository you might want to either copy configs for new modules to data-only container manually or add corresponding check and copy configs automatically o container start by extending your custom image).

> So both of my extensions are missing, which is normal, but quite inconvenient. I have to reinstall them, and even more because all the extensions installed for the php container are missing from the php cli of the ssh container.

The decision was made this way because you're not supposed to ever (under normal conditions) enter any other image except SSH one (and all of the CRON tasks are running in SSH container as well). You can, of course, copy Composer to PHP image and extend it in either way if you feel any need for this in your use case.

**Comment by noglitchyo** [comment]
Thank your for your reply. It makes things a bit more clear for me and I achieved to install both of my extensions and it is working like a charm now.

But I am still not sure to understand the things with the SSH container. 
Is there a way to use the php-cli installed in the php container but using the SSH container or are we forced to used the php-cli installed in the ssh container? I am not sure to be clear in what I am saying. Tell me if you don't understand my problem. 

Thanks for your time.

**Comment by nazar-pc** [comment]
CLI is CLI, you need to be inside of container were you want to execute it (roughly speaking). Since php container is only used from external as FastCGI service, you don't have direct access for running CLI commands there.
In most cases this shouldn't be a problem, you can run Composer or anything else from SSH container. Having them separated allows few important things:
* reuse official PHP images and thus receive security updates quickly as they are released
* upgrade containers when needed
* have everything decoupled so that you can potentially scale to multiple SSH/PHP/MariaDB/Nginx/etc. containers (this is highly experimental and probably not working with modern Docker version yet)

**Comment by noglitchyo** [comment]
Alright thanks, You made it all clear.
