### ISSUE TITLE
pagespeed module

### ISSUE THREAD

**Issue by un-precedented** [nazar-pc/docker-webserver#26]
how about adding pagespeed module in the nginx container?

**Comment by nazar-pc** [comment]
TL;DR: It is not present and there are no plans to add it ever.

Nginx image shipped here is very close to upstream `nginx` image from Docker Hub. I do not add any additional modules and do not remove anything already installed.
For `ngx_pagespeed` you need to recompile Nginx from source, which wouldn't be a trivial process if you're asking this. Upstream image uses binary packages, so you'll need to build from sources with all of the configs used by upstream packaged version in order to make it almost 100% compatible with image found in this repository.

**Comment by un-precedented** [comment]
is this the upstream image? https://hub.docker.com/r/joelcox22/nginx-upstream/

**Comment by nazar-pc** [comment]
Yes and no. This repository uses image (that I called upstream) from Docker team: https://hub.docker.com/r/_/nginx/

Mentioned image is kind of similar, but uses Alpine instead of Debian. You need to browse for image that builds from source code and modify it so that it will also build `ngx_pagespeed` module for you. But honestly, I didn't make it previously so can't help you too much here.
